apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: devops-argocd
  namespace: config-management-system
  annotations:
    configsync.gke.io/cluster-name-selector: prod-devops-runtime-0e05-europe-north1-prod-devops-runtime
spec:
  sourceType: helm
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  helm:
    repo: https://argoproj.github.io/argo-helm
    chart: argo-cd
    version: 7.7.11
    releaseName: argocd
    namespace: argocd
    values:
      redis-ha:
        enabled: true
        tolerations:
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 300
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 300
          - effect: NoSchedule
            key: kubernetes.io/arch
            operator: Equal
            value: amd64
      controller:
        replicas: 1
      server:
        autoscaling:
          enabled: true
          minReplicas: 2
      repoServer:
        autoscaling:
          enabled: true
          minReplicas: 2
      applicationSet:
        replicas: 2
    auth: none