apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: devops-argocd
  namespace: argocd
spec:
  sourceType: helm
  # Since this is for a namespace repository, the format is unstructured
  sourceFormat: unstructured
  helm:
    repo: https://argoproj.github.io/argo-helm
    chart: argo/argo-cd
    version: 7.7.11
    releaseName: argocd
    namespace: argocd
    values:
      redis-ha:
        enabled: true
      controller:
        replicas: 1
      server:
        autoscaling:
          enabled: true
          minReplicas: 2
      repoServer:
        autoscaling:
          enabled: true
          minReplicas: 2
      applicationSet:
        replicas: 2
    includeCRDs: HELM_INCLUDE_CRDS
    auth: none
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: ns-reconciler-argocd-devops-argocd-13
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
