---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: order-topic-sub
  annotations:
    cnrm.cloud.google.com/project-id: prod-team-b-8c36
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: order-topic
  deadLetterPolicy:
    deadLetterTopicRef:
      name: order-topic-sub-dlq
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: order-topic-sub-dlq
  annotations:
    cnrm.cloud.google.com/project-id: prod-team-b-8c36
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: order-topic-sub-dlq-sub
  annotations:
    cnrm.cloud.google.com/project-id: prod-team-b-8c36
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: order-topic-sub-dlq
