apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: istio-ingressgateway
  namespace: ingress-gateway
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 15021
    type: HTTP
    requestPath: /healthz/ready