apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        # This is required to tell Anthos Service Mesh to inject the gateway with the
        # required configuration.
        inject.istio.io/templates: gateway
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
    spec:
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
          - name: status-port
            protocol: TCP
            containerPort: 15021
          - name: http2
            protocol: TCP
            containerPort: 80
          - name: https
            protocol: TCP
            containerPort: 443
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: status-port
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: status-port
      serviceAccountName: istio-ingressgateway