apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        # This is required to tell Anthos Service Mesh to inject the gateway with the
        # required configuration.
        inject.istio.io/templates: gateway
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
    spec:
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
          # ports:
          #   - name: status-port
          #     port: 15021
          #     protocol: TCP
          #     containerPort: 15021
          #   - name: http2
          #     port: 80
          #     protocol: HTTP
          #     containerPort: 80
          #   - name: https
          #     port: 443
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 15021
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: 15021
      serviceAccountName: istio-ingressgateway