---
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: config-connector
  namespace: config-management-system
  annotations:
    configsync.gke.io/cluster-name-selector: prod-app-runtime-6e3b-europe-north1-prod-app-runtime
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/Predictly/gke-enterprise
    branch: main
    dir: config-connector/operator-system/
    auth: none
---
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: config-connector-crds
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/Predictly/gke-enterprise
    branch: main
    dir: config-connector/crds/v1_127_0/
    auth: none
