apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  annotations:
    configsync.gke.io/cluster-name-selector: prod-devops-runtime
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: devops
  namespace: argocd
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/Predictly/gke-enterprise
    branch: main
    dir: devops/
    auth: none
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: ns-reconciler-argocd-devops-argocd-13
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-cm
  annotations:
    configmanagement.gke.io/namespace-selector: team-devops-scope
data:
  key: value
