---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: common-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      # All namespaces managed by config sync
      predictly.se/fleet: "true"
