apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: common-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      # All namespaces managed by config sync
      app.kubernetes.io/managed-by: configmanagement.gke.io
---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-devops-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-devops
---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-a-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-a
---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-b-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-b