apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-a-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-a
---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-b-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-b