---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-network-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-network
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: team-network-repo
  annotations:
    configmanagement.gke.io/namespace-selector: team-network-scope
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/Predictly/gke-enterprise
    branch: main
    dir: network/
    auth: none
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-gateway-team-network-repo-cluster-admin
  namespace: ingress-gateway
subjects:
- kind: ServiceAccount
  name: ns-reconciler-ingress-gateway-team-network-repo-17
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io