---
apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
   name: team-b-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: team-b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: team-b-app-cm
  annotations:
    configmanagement.gke.io/namespace-selector: team-b-scope
data:
  key: team-b